@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ExportScheduleCommandParser" as ExportScheduleCommandParser LOGIC_COLOR
participant ":ExportScheduleCommand" as ExportScheduleCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":JsonUtil" as JsonUtil STORAGE_COLOR
end box

[-> LogicManager : execute("exportSchedule 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("exportSchedule 1")
activate AddressBookParser

create ExportScheduleCommandParser
AddressBookParser -> ExportScheduleCommandParser
activate ExportScheduleCommandParser

ExportScheduleCommandParser --> AddressBookParser
deactivate ExportScheduleCommandParser

AddressBookParser -> ExportScheduleCommandParser : parse("1")
activate ExportScheduleCommandParser

create ExportScheduleCommand
ExportScheduleCommandParser -> ExportScheduleCommand
activate ExportScheduleCommand

ExportScheduleCommand --> ExportScheduleCommandParser
deactivate ExportScheduleCommand

ExportScheduleCommandParser --> AddressBookParser
deactivate ExportScheduleCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ExportScheduleCommandParser -[hidden]-> AddressBookParser
destroy ExportScheduleCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> ExportScheduleCommand : execute()
activate ExportScheduleCommand

ExportScheduleCommand -> JsonUtil : saveJsonFile()
activate JsonUtil

JsonUtil --> ExportScheduleCommand
deactivate JsonUtil

create CommandResult
ExportScheduleCommand -> CommandResult
activate CommandResult

CommandResult --> ExportScheduleCommand
deactivate CommandResult

ExportScheduleCommand --> LogicManager : result
deactivate ExportScheduleCommand

[<--LogicManager
deactivate LogicManager
@enduml
