@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindCommonTimingCommandParser" as FindCommonTimingCommandParser LOGIC_COLOR
participant ":FindCommonTimingCommand" as FindCommonTimingCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("findCommonTiming t/friends da/2022-12-28")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("findCommonTiming t/friends da/2022-12-28")
activate AddressBookParser

create FindCommonTimingCommandParser
AddressBookParser -> FindCommonTimingCommandParser
activate FindCommonTimingCommandParser

FindCommonTimingCommandParser --> AddressBookParser
deactivate FindCommonTimingCommandParser

AddressBookParser -> FindCommonTimingCommandParser : parse("t/friends da/2022-12-28")
activate FindCommonTimingCommandParser

create FindCommonTimingCommand
FindCommonTimingCommandParser -> FindCommonTimingCommand :predicate
activate FindCommonTimingCommand

FindCommonTimingCommand --> FindCommonTimingCommandParser
deactivate FindCommonTimingCommand

FindCommonTimingCommandParser --> AddressBookParser
deactivate FindCommonTimingCommandParser

FindCommonTimingCommandParser -[hidden]-> AddressBookParser
destroy FindCommonTimingCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> FindCommonTimingCommand : execute()
activate FindCommonTimingCommand

FindCommonTimingCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> FindCommonTimingCommand
deactivate Model

create CommandResult
FindCommonTimingCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommonTimingCommand
deactivate CommandResult

FindCommonTimingCommand --> LogicManager : result
deactivate FindCommonTimingCommand

[<--LogicManager
deactivate LogicManager
@enduml
