@startuml
start
:User executes freeSchedule command;

:FreeScheduleCommandParser parses the user input;

if () then ([hasTimePrefix and hasDatePrefix])
    :Get the user specified
    time and date;
    :Create IsPersonFreePredicate;
    :Filter model with predicate;
else ([else])
    if () then ([hasTimePrefix])
    :Get the user specified time
    and set date to today;
    :Create IsPersonFreePredicate;
    :Filter model with predicate;
    else ([else])
    :Throw exception regarding
    missing prefix or invalid arguments;
    endif
endif
stop
@enduml