@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ViewGroupCommandParser" as ViewGroupCommandParser LOGIC_COLOR
participant ":ViewGroupCommand" as ViewGroupCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("viewGroup t/friends")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("viewGroup t/friends")
activate AddressBookParser

create ViewGroupCommandParser
AddressBookParser -> ViewGroupCommandParser
activate ViewGroupCommandParser

ViewGroupCommandParser --> AddressBookParser
deactivate ViewGroupCommandParser

AddressBookParser -> ViewGroupCommandParser : parse("t/friends")
activate ViewGroupCommandParser

create ViewGroupCommand
ViewGroupCommandParser -> ViewGroupCommand :predicate
activate ViewGroupCommand

ViewGroupCommand --> ViewGroupCommandParser
deactivate ViewGroupCommand

ViewGroupCommandParser --> AddressBookParser
deactivate ViewGroupCommandParser

ViewGroupCommandParser -[hidden]-> AddressBookParser
destroy ViewGroupCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> ViewGroupCommand : execute()
activate ViewGroupCommand

ViewGroupCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> ViewGroupCommand
deactivate Model

create CommandResult
ViewGroupCommand -> CommandResult
activate CommandResult

CommandResult --> ViewGroupCommand
deactivate CommandResult

ViewGroupCommand --> LogicManager : result
deactivate ViewGroupCommand

[<--LogicManager
deactivate LogicManager
@enduml
